name: MIUI
on:
  workflow_call:
  workflow_dispatch:

jobs:
   build-project:
    runs-on: ubuntu-latest

    steps:
    - name: setting configurasi
      uses: actions/checkout@v4

    - name: setup environment
      run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
    - name: ready compile...
      run: |
          chmod +x miui.sh
          bash miui.sh
